[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8.0", "wheel", "Cython"]
[project]
name = "differential_verification"
# version = "0.1"
dynamic = ["version"]
dependencies = [
   "cython",
   "icecream",
   "ipython",
   "pyapproxmc",
   "pycryptosat",
   "sat_toolkit>=0.3.5",
   "setuptools",
   "tqdm",
]
requires-python = ">=3.9"
authors = [
  {name = "Marcel Nageler", email = "marcel.nageler@iaik.tugraz.at"},
  {name = "Shibam Ghosh", email = "shibam.math@gmail.com"},
]
description = "A tool for verifying differential characteristics in block ciphers"
readme = "README.md"
license = {file = "LICENSE.txt"}
classifiers = [
   "License :: OSI Approved :: MIT License",
   "Operating System :: POSIX :: Linux",
   "Operating System :: MacOS",
   "Programming Language :: Python",
   "Programming Language :: Cython",
   "Programming Language :: C",
   "Framework :: Pytest",
]
[tool.setuptools.package-data]
differential_verification = ["**/log_config.json"]
[project.scripts]
verify-characteristic = "differential_verification.main:main"
[tool.setuptools_scm]
root = ".."
version_file = "src/differential_verification/_version.py"