name: Run Pytest

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.6", "3.7", "3.8", "3.9"]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: git clone https://github.com/classabbyamp/espresso-logic.git /tmp/espresso-logic \
              && cd /tmp/espresso-logic/espresso-src \
              && make CFLAGS=-O3 \
              && install -m 755 ../bin/espresso /usr/bin/espresso \
              && rm -rf /tmp/espresso-logic
      - name: Install dependencies
        run: pip install . ./tests
      - name: Install dependencies
        run: pip install pytest pytest-md pytest-emoji
      - uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: false
          job-summary: true
