name: Run Pytest

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.6", "3.7", "3.8", "3.9"]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install APT dependencies
        run: |
          apt-get update
          apt-get install -y build-essential cmake gcc git libboost-program-options-dev libboost-serialization-dev libgmp3-dev libmpfr-dev libntl-dev zlib1g-dev

      - name: Install Espresso
        run: |
          git clone https://github.com/classabbyamp/espresso-logic.git /tmp/espresso-logic
          cd /tmp/espresso-logic/espresso-src
          make CFLAGS=-O3
          sudo install -m 755 ../bin/espresso /usr/bin/espresso
          rm -rf /tmp/espresso-logic

      - name: Install Cryptominisat
        run: |
          export CRYPTOMINISAT_VERSION=5.11.21
          mkdir /tmp/sat
          cd /tmp/sat
          git clone https://github.com/msoos/cryptominisat
          cd cryptominisat
          git checkout tags/${CRYPTOMINISAT_VERSION}
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          sudo make install
          sudo ldconfig
          rm -rf /tmp/sat

      - name: Install Arjun
        run: |
          export ARJUN_VERSION=2.5.4
          mkdir /tmp/sat
          cd /tmp/sat
          git clone https://github.com/meelgroup/arjun
          cd arjun
          git checkout tags/${ARJUN_VERSION}
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          sudo make install
          sudo ldconfig
          rm -rf /tmp/sat

      - name: Install ApproxMC
        run: |
          export APPROXMC_VERSION=4.1.24
          mkdir /tmp/sat
          cd /tmp/sat
          git clone https://github.com/meelgroup/approxmc
          cd approxmc
          git checkout tags/${APPROXMC_VERSION}
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          sudo make install
          sudo ldconfig
          rm -rf /tmp/sat


      - name: Install dependencies
        run: pip install . ./tests
      - name: Install dependencies
        run: pip install pytest pytest-md
      - uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          verbose: false
          job-summary: true
